DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS places;
DROP TABLE IF EXISTS regions;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE places (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    place_name TEXT UNIQUE NOT NULL,
    region_id INTEGER
);

CREATE TABLE regions (
    id INTEGER PRIMARY KEY,
    region_name TEXT UNIQUE NOT NULL
);